name: DEPLOY

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  pull-requests: write

concurrency: product_environment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Set the installed PHP version of the server here

      - name: Install dependencies
        run: |
          composer config github-oauth.github.com ${{ secrets.ACCESS_TOKEN }}
          composer config bearer.packages.shopware.com ${{ secrets.SHOPWARE_TOKEN }}
          composer install --no-interaction --no-suggest --optimize-autoloader

      - name: Build deploy directory
        run: |
          mkdir ../build
          cp -r custom ../build
          tar -cvf deploy.tar ../build

      - name: Prepare Deployment DEV
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USER_DEV }}
          password: ${{ secrets.SSH_PW_DEV }}
          source: "deploy.tar"
          target: ${{ secrets.SSH_TARGET_DEV }}

      - name: Finish Deployment DEV
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USER_DEV }}
          password: ${{ secrets.SSH_PW_DEV }}
          script: |
            cd ${{ secrets.SSH_TARGET_DEV }}
            rm -rf custom/plugins*
            tar -xvf deploy.tar
            rsync -av build/* ${{ secrets.SSH_TARGET_DEV }}
            mkdir -p custom/plugins
            touch install.lock
            rm deploy.tar
            php bin/console database:migrate --all
            chmod +x bin/build-storefront.sh
            ./bin/build-storefront.sh
            php bin/console cache:clear
            php bin/console system:generate-jwt-secret

      - name: Prepare Deployment MAIN
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_MAIN }}
          username: ${{ secrets.SSH_USER_MAIN }}
          password: ${{ secrets.SSH_PW_MAIN }}
          source: "deploy.tar"
          target: ${{ secrets.SSH_TARGET_MAIN }}

      - name: Finish Deployment MAIN
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_MAIN }}
          username: ${{ secrets.SSH_USER_MAIN }}
          password: ${{ secrets.SSH_PW_MAIN }}
          script: |
            cd ${{ secrets.SSH_TARGET_MAIN }}
            rm -rf bin/*
            rm -rf config/*
            rm -rf custom/*
            rm -rf vendor/*
            tar -xvf deploy.tar
            rsync -av build/* ${{ secrets.SSH_TARGET_MAIN }}
            mkdir -p files
            mkdir -p custom/plugins
            mkdir -p custom/apps
            mkdir -p custom/static-plugins
            mkdir -p var/queue
            mkdir -p var/test
            touch install.lock
            rm deploy.tar
            rm -rf build/
            /usr/bin/php8.2 bin/console database:migrate --all
            chmod +x bin/build-storefront.sh
            ./bin/build-storefront.sh
            /usr/bin/php8.2 bin/console cache:clear
            /usr/bin/php8.2 bin/console system:generate-jwt-secret
